# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCasodeprueba132():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_casodeprueba132(self):
    self.driver.get("http://localhost:1111/product/nike-free-run-2018")
    self.driver.set_window_size(789, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-block").click()
    self.driver.find_element(By.LINK_TEXT, "Cart 1").click()
    assert self.driver.find_element(By.ID, "shipping-amount").text == "FREE shipping"
    self.driver.find_element(By.CSS_SELECTOR, ".pushy-link").click()
    self.driver.close()
  
