# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCasodeprueba2041():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_casodeprueba2041(self):
    self.driver.get("http://localhost:1111/admin/products")
    self.driver.set_window_size(789, 816)
    self.driver.find_element(By.ID, "btn_product_filter").click()
    assert self.driver.find_element(By.ID, "notify_message").text == "Please enter a keyword to filter"
    self.driver.close()
  
