# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHU19PE02():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hU19PE02(self):
    self.driver.get("http://localhost:1111/admin/users")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(9) a:nth-child(3)").click()
    self.driver.find_element(By.ID, "usersName").click()
    self.driver.find_element(By.ID, "usersName").send_keys("#Juan Silva123")
    self.driver.find_element(By.ID, "userPassword").click()
    self.driver.find_element(By.ID, "userPassword").send_keys("Juansilva123!")
    self.driver.find_element(By.CSS_SELECTOR, "#userEditForm > .form-group:nth-child(5) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, "#userEditForm > .form-group:nth-child(5) > .form-control").send_keys("Juansilva123!")
    self.driver.find_element(By.ID, "btnUserEdit").click()
    assert self.driver.find_element(By.ID, "notify_message").text == "El campo user name no puede contener caracteres especiales"
  
