# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHU19PE01():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hU19PE01(self):
    self.driver.get("http://localhost:1111/admin/dashboard")
    self.driver.set_window_size(1296, 688)
    self.driver.find_element(By.LINK_TEXT, "Users").click()
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3) a:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-9").click()
    self.driver.find_element(By.ID, "usersName").send_keys("Nicolas ")
    self.driver.find_element(By.ID, "usersName").send_keys("Nicolas Garces")
    self.driver.find_element(By.ID, "userPassword").click()
    self.driver.find_element(By.ID, "userPassword").send_keys("Nicolasgarces123!")
    self.driver.find_element(By.CSS_SELECTOR, "#userEditForm > .form-group:nth-child(5) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, "#userEditForm > .form-group:nth-child(5) > .form-control").send_keys("Nicolasgarces123!")
    self.driver.find_element(By.ID, "btnUserEdit").click()
    assert self.driver.find_element(By.ID, "notify_message").text == "User account updated"
  
