# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCasodeprueba432():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_casodeprueba432(self):
    self.driver.get("http://localhost:1111/admin/settings/discounts")
    self.driver.set_window_size(968, 720)
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-12").click()
    self.driver.find_element(By.LINK_TEXT, "New Discount").click()
    self.driver.find_element(By.ID, "discountCode").click()
    self.driver.find_element(By.ID, "discountCode").send_keys("code2222")
    self.driver.find_element(By.ID, "discountType").click()
    dropdown = self.driver.find_element(By.ID, "discountType")
    dropdown.find_element(By.XPATH, "//option[. = 'Percent']").click()
    self.driver.find_element(By.ID, "discountValue").click()
    self.driver.find_element(By.ID, "discountValue").send_keys("-20")
    self.driver.find_element(By.CSS_SELECTOR, ".col-12:nth-child(5) .gj-icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".col-12:nth-child(5) .gj-icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .current-month:nth-child(5) > div").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gj-modal:nth-child(19) .btn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-12:nth-child(6) .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > .current-month:nth-child(5) > div").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gj-modal:nth-child(20) .btn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-success:nth-child(1)").click()
    assert self.driver.find_element(By.ID, "notify_message").text == "Error! Discount value negativo"
    self.driver.close()
  
