# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCasodeprueba41():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_casodeprueba41(self):
    self.driver.get("http://localhost:1111/")
    self.driver.set_window_size(968, 720)
    self.driver.find_element(By.CSS_SELECTOR, ".col-6:nth-child(2) .img-fluid").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".qty-btn-plus")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-block").click()
    elements = self.driver.find_elements(By.ID, "notify_message")
    assert len(elements) > 0
  
