# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHU171():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hU171(self):
    self.driver.get("http://localhost:1111/")
    self.driver.set_window_size(945, 1020)
    self.driver.find_element(By.ID, "dropdownMenuButton").click()
    self.driver.find_element(By.LINK_TEXT, "Italiano").click()
    self.driver.find_element(By.LINK_TEXT, "Clothing").click()
    assert self.driver.find_element(By.ID, "notify_message").text == "404 Error - Pagina non trovata"
  
